## Module 3: Neural Networks & PyTorch
Welcome to deep learning! In this module, we will explore how machines learn by mimicking the structure of the human brain. We will transition from standard data analysis into building models that can recognize patterns, culminating in using PyTorch, the industry-standard framework for deep learning.

## Prerequisite: Installing PyTorch
Before we begin, we need to install PyTorch into your virtual environment.

Ensure your venv is activated in the VS Code terminal.

Run the following command to install the CPU version of PyTorch and torchvision (which contains computer vision datasets):

pip install torch torchvision

(Note: If you have a dedicated NVIDIA GPU and want GPU acceleration, the installation command differs slightly, but the standard CPU version is perfectly fine for learning!)

## Lesson 1: The Perceptron (The Artificial Neuron)
A neural network is made up of interconnected nodes called neurons (or perceptrons).Here is how a single artificial neuron makes a decision:Inputs ($x$): Data enters the neuron (e.g., the pixels of an image).Weights ($w$): Each input is assigned a weight, representing its importance.Bias ($b$): A constant value added to shift the result.Activation Function: The neuron calculates the sum of its inputs multiplied by their weights, adds the bias, and passes it through a mathematical filter (like "ReLU" or "Sigmoid") to decide if the neuron should "fire" (activate).

## Lesson 2: Gradient Descent and Backpropagation
How does a neural network actually "learn"? It learns by making predictions, measuring how wrong they are, and adjusting its weights.The Loss Function: This calculates the "Error". A common loss function for regression is Mean Squared Error (MSE):$$MSE = \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2$$Where $y_i$ is the actual value, and $\hat{y}_i$ is the network's prediction.Gradient Descent: Imagine standing on a foggy mountain and wanting to reach the bottom (zero error). You take a step in the direction that goes down the fastest. This "downward slope" is the mathematical gradient.Backpropagation: The network works backward from the output, calculating the gradient for every single weight, and updating them slightly to reduce the error for the next prediction.

## Lesson 3: Introduction to PyTorch Tensors
PyTorch uses Tensors. They are almost identical to NumPy arrays, but with two massive upgrades: they can run on ultra-fast GPUs, and they automatically calculate gradients (derivatives) for you during backpropagation.

In [1]:
import torch
import numpy as np

# Creating a Tensor
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]], requires_grad=True)
print("PyTorch Tensor:\n", x)

# Math works just like NumPy
y = x * 10
print("\nMultiplied by 10:\n", y)

# The Magic of PyTorch: Auto-Gradients
# Let's calculate a single value (the mean) and run backpropagation
out = y.mean()
out.backward() # This automatically calculates the slopes!

print("\nGradients (how much each value contributed to the output):\n", x.grad)

PyTorch Tensor:
 tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

Multiplied by 10:
 tensor([[10., 20.],
        [30., 40.]], grad_fn=<MulBackward0>)

Gradients (how much each value contributed to the output):
 tensor([[2.5000, 2.5000],
        [2.5000, 2.5000]])


## Lesson 4: Building a Deep Learning Model
Instead of building complex math by hand, PyTorch provides the torch.nn module to snap neural network layers together like Lego bricks.

In [2]:
import torch.nn as nn

# Building a simple feed-forward neural network
model = nn.Sequential(
    nn.Linear(in_features=10, out_features=5), # Hidden Layer 1
    nn.ReLU(),                                 # Activation Function
    nn.Linear(in_features=5, out_features=1)   # Output Layer
)

print(model)

# Passing dummy data through the model
dummy_input = torch.randn(1, 10) # 1 row, 10 columns of random numbers
prediction = model(dummy_input)
print("\nModel Prediction:", prediction.item())

Sequential(
  (0): Linear(in_features=10, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=1, bias=True)
)

Model Prediction: -0.15906211733818054
